# Copyright 2024 Duskphantom Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Build And Test
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Test-Actions:
    runs-on: compiler-ci
    container:
      image: c-ci:latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: http://43.136.17.142:3000/actions/checkout@v3
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Build Rust code
        run: cargo build --verbose
      - name: Test Rust code
        run: cargo test --verbose
      - name: Build Rust code for release
        run: cargo build --release --verbose
      - name: Test Rust code for release
        run: cargo test --release --verbose
      - name: Check for clippy warnings
        run: cargo clippy -- -D warnings
      # - name: Check code formatting
      #   run: cargo fmt --all -- --check
