name: Build And Test
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Test-Actions:
    runs-on: compiler-ci
    container:
      image: c-ci:latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: http://43.136.17.142:3000/actions/checkout@v3
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Build Rust code
        run: cargo build --verbose
      - name: Test Rust code
        run: cargo test --verbose
      - name: Build Rust code for release
        run: cargo build --release --verbose
      - name: Test Rust code for release
        run: cargo test --release --verbose
      - name: Check for clippy warnings
        run: cargo clippy --all-targets --all-features -- -D warnings
      # - name: Check code formatting
      #   run: cargo fmt --all -- --check
