declare dso_local i32 @getint()
declare dso_local i32 @getch()
declare dso_local float @getfloat()
declare dso_local i32 @getarray(ptr noundef %0)
declare dso_local i32 @getfarray(ptr noundef %0)
declare dso_local void @putint(i32 noundef %0)
declare dso_local void @putch(i32 noundef %0)
declare dso_local void @putarray(i32 noundef %0, ptr noundef %1)
declare dso_local void @putfloat(float noundef %0)
declare dso_local void @putfarray(i32 noundef %0, ptr noundef %1)
declare dso_local void @putf(ptr noundef %0, ...)
declare dso_local void @starttime()
declare dso_local void @stoptime()