[package]
name = "duskphantom-graph"
version = "0.0.2"
edition = "2021"
description = "Graph Utills for duskphantom project"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
